# Generated by Django 3.1.3 on 2020-11-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotzoneBackend',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('coordinateX', models.DecimalField(
                    decimal_places=8, max_digits=20)),
                ('coordinateY', models.DecimalField(
                    decimal_places=8, max_digits=20)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
