# Generated by Django 3.1.3 on 2020-11-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone_backend', '0003_auto_20201103_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotzonebackend',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
